### ISSUE TITLE
Update to Jellyfin 10.8.0

### ISSUE THREAD

**Issue by LePips** [jellyfin/jellyfin-sdk-swift#3]
Needs to be updated to 10.8.0. Necessary for work https://github.com/jellyfin/Swiftfin/issues/288 and overall support.

@PangMo5 What's the status of https://github.com/jellyfin/Swiftfin/issues/277? If we need to start over, that's fine. Moving to async/await isn't at the top of my list right now, however will be something that we need to do before launch imo.

At the same time, you probably know more about how to update this to 10.8.0 so I may have to ask you to do this, but it isn't urgent.

**Comment by PangMo5** [comment]
Okay, it hasn't progressed much yet, but I'll look at it again over the weekend. 😄

**Comment by PangMo5** [comment]
Since the structure change PR is scheduled like [A](https://github.com/jellyfin/Swiftfin/pull/452),
I will proceed with the async await response that can change the structure of the ViewModel a lot later, and i will update it to respond to 10.8.0 using the existing method at now.

**Comment by PangMo5** [comment]
Since the structure change PR is scheduled like https://github.com/jellyfin/Swiftfin/pull/452,
I will proceed a lot later with the async await response that can change the structure of the ViewModel and etc, 
and i will update it to respond to 10.8.0 using the existing method for now.

**Comment by PangMo5** [comment]
#4
