### ISSUE TITLE
CollectionType and CollectionTypeOptions case

### ISSUE THREAD

**Issue by jnorris441** [jellyfin/jellyfin-sdk-swift#34]
Jellyfin has two "collection type" enums...lowercase CollectionType and Pascal case CollectionTypeOptions. I assume they are used for different things.

When requesting /Library/VirtualFolders you get back a lowercase CollectionType (which is marked as CollectionTypeOptions in the spec)

```
[
    {
        "Name": "Movies",
        "Locations": [
            "H:\\tobemoved"
        ],
        "CollectionType": "movies",
        ...
```

This leads to a JSON decoding error.

Is the API spec incorrect?

**Comment by LePips** [comment]
What server version are you using? Related:

- https://github.com/jellyfin/jellyfin/pull/9764
- https://github.com/jellyfin/jellyfin/pull/10702

**Comment by jnorris441** [comment]
@LePips  Windows 10.8.13, the latest on the Jellyfin site (from November)

**Comment by LePips** [comment]
This may be technically a server issue, but I can possibly add a patching step in the generation to make it properly decode.

**Comment by jnorris441** [comment]
that was quick thank you
