### ISSUE TITLE
Add PersonKind

### ISSUE THREAD

**Issue by JPKribs** [jellyfin/jellyfin-sdk-swift#40]
New to the SDK side of this so let me know if this isn't the right place!

I'm completely clueless when it comes to SDK generation and patch files but it would be nice to have PersonKinds / PersonType in the SDK. I think this would be helpful for the Cast & Crew sections for clients.

Here is what I made for use in Swiftfin:

```
enum PersonKind: String, CaseIterable {
    case unknown = ""
    case actor = "Actor"
    case director = "Director"
    case composer = "Composer"
    case writer = "Writer"
    case guestStar = "GuestStar"
    case producer = "Producer"
    case conductor = "Conductor"
    case lyricist = "Lyricist"
    case arranger = "Arranger"
    case engineer = "Engineer"
    case mixer = "Mixer"
    case remixer = "Remixer"
    case creator = "Creator"
    case artist = "Artist"
    case albumArtist = "AlbumArtist"
    case author = "Author"
    case illustrator = "Illustrator"
    case penciller = "Penciller"
    case inker = "Inker"
    case colorist = "Colorist"
    case letterer = "Letterer"
    case coverArtist = "CoverArtist"
    case editor = "Editor"
    case translator = "Translator"
}
```

My source for this can be found here: https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Data/Enums/PersonKind.cs.

**Comment by LePips** [comment]
`PersonKind` is provided in the 10.9 generation, which we will get when we update the SDK in SF.

https://github.com/jellyfin/jellyfin-sdk-swift/blob/a0e848a7aaec55991610818de6128b15cfcec725/Sources/Entities/PersonKind.swift#L12
