### ISSUE TITLE
'JellyfinAPI' is deprecated: renamed to 'JellyfinAPIAPI'

### ISSUE THREAD

**Issue by ddevler** [jellyfin/jellyfin-sdk-swift#6]
Is this correct or an issue with current export? I updated the main branch from old 10.7 to current 10.8

Code triggered the message. Seems kinda odd to rename it to "JellyfinAPIAPI".
`JellyfinAPI.customHeaders["X-Emby-Authorization"] = header`

**Comment by LePips** [comment]
This is a generation from the OpenAPI generator (the entire file was generated and comment left by OpenAPI):

https://github.com/jellyfin/jellyfin-sdk-swift/blob/9d6e46b94d2178116ee3546b03dfb67e19e3a93a/Sources/JellyfinAPI/APIs.swift#L9-L14
